name: shared
description: Shared models, services, and utilities for the Taxi App
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.5.0
  firebase_core: ^3.12.0
  geolocator: ^13.0.2
  cloud_functions: ^5.3.0
  url_launcher: ^6.3.1
